version: "{build}"
branches:
  except:
    - gh-pages
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g npm
  - npm --version
  - npm install
test_script:
  - set NODE_ENV=production
  - npm run build
  - set NODE_ENV=test
  - npm test
build: off
deploy: off
environment:
  matrix:
    - nodejs_version: 5
